# Generated by Django 5.2.10 on 2026-02-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('itemName', models.CharField(max_length=20)),
                ('orderQty', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('deliveryAddress', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
